source 'https://rubygems.org'

ruby '>= 2.3.5', '< 2.6'
gem 'pg', '~> 0.18' 
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
#gem 'sqlite3'
gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'rack-flash3'
gem 'tux'
gem 'bcrypt'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'sinatra-twitter-bootstrap', :require => 'sinatra/twitter-bootstrap'
gem 'capybara'
gem 'require_all'
